#!/bin/bash

echo "🔧 解决 Git 推送问题的几种方法"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "方法一：禁用 HTTP/2 协议（推荐）"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# 运行以下命令："
echo "git config --global http.version HTTP/1.1"
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "方法二：增加缓冲区大小"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# 运行以下命令："
echo "git config --global http.postBuffer 524288000"
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "方法三：使用 SSH 而不是 HTTPS（最稳定）"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# 1. 更改远程仓库 URL 为 SSH："
echo "git remote set-url origin git@github.com:NamelessCrew/astrobo.github.io.git"
echo ""
echo "# 2. 如果还没有 SSH 密钥，需要先设置："
echo "ssh-keygen -t ed25519 -C \"your_email@example.com\""
echo "cat ~/.ssh/id_ed25519.pub"
echo "# 复制输出的公钥，添加到 GitHub: Settings → SSH and GPG keys → New SSH key"
echo ""
echo "# 3. 推送："
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "方法四：分批推送（如果文件太大）"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# 推送时使用压缩："
echo "git config --global core.compression 9"
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "当前状态："
echo "════════════════════════════════════════════════════════════════"
echo "✅ 本地提交成功"
echo "✅ 远程仓库已配置: https://github.com/NamelessCrew/astrobo.github.io.git"
echo "❌ 推送失败（HTTP/2 错误）"
echo ""
echo "推荐先尝试方法一，如果不行再试方法三（SSH）"
