#!/bin/bash

echo "🔐 使用 SSH 推送到 GitHub（推荐方案）"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "步骤 1：复制 SSH 公钥"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "你的 SSH 公钥："
cat ~/.ssh/id_rsa.pub
echo ""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "步骤 2：添加到 GitHub"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. 访问：https://github.com/settings/keys"
echo "2. 点击 'New SSH key'"
echo "3. Title: 填写 'My Mac' 或任意名称"
echo "4. Key: 粘贴上面显示的公钥（整行）"
echo "5. 点击 'Add SSH key'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "步骤 3：测试 SSH 连接并推送"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "运行以下命令："
echo ""
echo "cd ~/my-homepage"
echo "ssh -T git@github.com"
echo "git remote set-url origin git@github.com:NamelessCrew/astrobo.github.io.git"
echo "git push -u origin main"
echo ""
echo "════════════════════════════════════════════════════════════════"
